    let paises = {
    europa: [
        { nom: "España", lat: 40, lon: -3 },
        { nom: "Alemania", lat: 52, lon: 13 },
        { nom: "Austria", lat: 48, lon: 16 },
        { nom: "Bélgica", lat: 50, lon: 4 },
        { nom: "Bulgaria", lat: 42, lon: 25 },
        { nom: "Chequia", lat: 49, lon: 15 },
        { nom: "Chipre", lat: 35, lon: 33 },
        { nom: "Croacia", lat: 45, lon: 16 },
        { nom: "Dinamarca", lat: 55, lon: 9 },
        { nom: "Eslovaquia", lat: 48, lon: 17 },
        { nom: "Eslovenia", lat: 46, lon: 14 },
        { nom: "Estonia", lat: 58, lon: 25 },
        { nom: "Finlandia", lat: 61, lon: 25 },
        { nom: "Francia", lat: 48, lon: 2 },
        { nom: "Grecia", lat: 38, lon: 23 },
        { nom: "Hungría", lat: 47, lon: 19 },
        { nom: "Irlanda", lat: 53, lon: -6 },
        { nom: "Italia", lat: 41, lon: 12 },
        { nom: "Letonia", lat: 56, lon: 24 },
        { nom: "Lituania", lat: 54, lon: 24 },
        { nom: "Luxemburgo", lat: 49, lon: 6 },
        { nom: "Malta", lat: 35, lon: 14 },
        { nom: "Paises Bajos", lat: 52, lon: 4 },
        { nom: "Polonia", lat: 52, lon: 21 },
        { nom: "Portugal", lat: 39, lon: -8 },
        { nom: "Rumanía", lat: 44, lon: 26 },
        { nom: "Suecia", lat: 59, lon: 17 },
        { nom: "Noruega", lat: 60, lon: 8 },
        { nom: "Reino Unido", lat: 51, lon: -1 },
        { nom: "Suiza", lat: 46, lon: 6 },
      ],
      africa: [
        { nom: "Angola", lat: -11, lon: 18 },
        { nom: "Argelia", lat: 30, lon: 1 },
        { nom: "Benín", lat: 7, lon: 2 },
        { nom: "Botsuana", lat: -22, lon: 24 },
        { nom: "Burkina Faso", lat: 11, lon: -1 },
        { nom: "Burundi", lat: -3, lon: 30 },
        { nom: "Cabo verde", lat: 16, lon: -25 },
        { nom: "Camerún", lat: 7, lon: 12 },
        { nom: "Chad", lat: 15, lon: 18 },
        { nom: "Comoras", lat: -12, lon: 43 },
        { nom: "Costa de Marfil", lat: 6, lon: -5 },
        { nom: "Egipto", lat: 30, lon: 30 },
        { nom: "Eritrea", lat: 14, lon: 40 },
        { nom: "Etiopia", lat: 9, lon: 40 },
        { nom: "Gabón", lat: -1, lon: 11 },
        { nom: "Gambia", lat: 13, lon: -16 },
        { nom: "Ghana", lat: 8, lon: -1 },
        { nom: "Guinea", lat: 9, lon: -10 },
        { nom: "Guinea Ecuatorial", lat: 1, lon: 10 },
        { nom: "Kenia", lat: 0, lon: 38 },
        { nom: "Lesoto", lat: -30, lon: 8 },
        { nom: "Liberia", lat: 6, lon: -9 },
        { nom: "Libia", lat: 31, lon: 14 },
        { nom: "Madagascar", lat: -19, lon: 37 },
        { nom: "Malaui", lat: -13, lon: 34 },
        { nom: "Malí", lat: 17, lon: -3 },
        { nom: "Marruecos", lat: 31, lon: -7 },
        { nom: "Mauricio", lat: -20, lon: 57 },
        { nom: "Mauritania", lat: 18, lon: -12 },
        { nom: "Mozambique", lat: -18, lon: 35 },
        { nom: "Namibia", lat: -23, lon: 16 },
        { nom: "Níger", lat: 17, lon: 8 },
        { nom: "Nigeria", lat: 9, lon: 8 },
        { nom: "República centroafricana", lat: 6, lon: 21 },
        { nom: "República del Congo", lat: -1, lon: 15 },
        { nom: "República Democrática del Congo", lat: -1, lon: 22 },
        { nom: "Ruanda", lat: -1, lon: 30 },
        { nom: "Santo Tomé", lat: 0, lon: 6 },
        { nom: "Senegal", lat: 14, lon: 0 },
        { nom: "Sierra Leona", lat: 0, lon: -14 },
        { nom: "Somalia", lat: 4, lon: 46 },
        { nom: "Sudáfrica", lat: -30, lon: 22 },
        { nom: "Sudán", lat: 12, lon: 30 },
        { nom: "Sudán del Sur", lat: 6, lon: 31 },
        { nom: "Tanzania", lat: -6, lon: 35 },
        { nom: "Togo", lat: 8, lon: 1 },
        { nom: "Túnez", lat: 34, lon: 9 },
        { nom: "Uganda", lat: 1, lon: 32 },
        { nom: "Zambia", lat: -13, lon: 27 },
        { nom: "Zimbabue", lat: -19, lon: 29 },
      ],
      america: [
        { nom: "Antigua y Barbuda", lat: 17, lon: -62 },
        { nom: "Argentina", lat: -39, lon: 63 },
        { nom: "Bahamas", lat: 25, lon: -77 },
        { nom: "Barbados", lat: 13, lon: -59 },
        { nom: "Belice", lat: 17, lon: -88 },
        { nom: "Bolivia", lat: -17, lon: -66 },
        { nom: "Brasil", lat: -12, lon: -42 },
        { nom: "Canadá", lat: 55, lon: -108 },
        { nom: "Chile", lat: -35, lon: -71 },
        { nom: "Colombia", lat: 4, lon: -74 },
        { nom: "Costa Rica", lat: 10, lon: -84 },
        { nom: "Cuba", lat: 21, lon: -78 },
        { nom: "Dominica", lat: 15, lon: -61 },
        { nom: "Ecuador", lat: -1, lon: -78 },
        { nom: "El Salvador", lat: 14, lon: -89 },
        { nom: "Estados Unidos", lat: 38, lon: -96 },
        { nom: "Guatemala", lat: 16, lon: -90 },
        { nom: "Guyana", lat: 5, lon: -59 },
        { nom: "Haití", lat: 19, lon: -72 },
        { nom: "Honduras", lat: 15, lon: -86 },
        { nom: "Jamaica", lat: 18, lon: -77 },
        { nom: "México", lat: 23, lon: -102 },
        { nom: "Nicaragua", lat: 13, lon: -85 },
        { nom: "Panamá", lat: 8, lon: -81 },
        { nom: "Paraguay", lat: -23, lon: -58 },
        { nom: "Perú", lat: -10, lon: -75 },
        { nom: "República Dominicana", lat: 19, lon: -70 },
        { nom: "Surinam", lat: 4, lon: -56 },
        { nom: "Trinidad", lat: 10, lon: -61 },
        { nom: "Uruguay", lat: -33, lon: -56 },
        { nom: "Venezuela", lat: 7, lon: -66 },
      ],
      asia: [
        { nom: "Afganistán", lat: 0, lon: 0 },
        { nom: "Arabia Saudita", lat: 0, lon: 0 },
        { nom: "Armenia", lat: 0, lon: 0 },
        { nom: "Azerbaiyán", lat: 0, lon: 0 },
        { nom: "Bangladés", lat: 0, lon: 0 },
        { nom: "Baréin", lat: 0, lon: 0 },
        { nom: "Birmania", lat: 0, lon: 0 },
        { nom: "Brunéi", lat: 0, lon: 0 },
        { nom: "Bután", lat: 0, lon: 0 },
        { nom: "Camboya", lat: 0, lon: 0 },
        { nom: "Catar", lat: 0, lon: 0 },
        { nom: "China", lat: 0, lon: 0 },
        { nom: "Chipre", lat: 0, lon: 0 },
        { nom: "Corea del Norte", lat: 0, lon: 0 },
        { nom: "Corea del Sur", lat: 0, lon: 0 },
        { nom: "Emiratos Arabes Unidos", lat: 0, lon: 0 },
        { nom: "Filipinas", lat: 0, lon: 0 },
        { nom: "Georgia", lat: 0, lon: 0 },
        { nom: "India", lat: 0, lon: 0 },
        { nom: "Indonesia", lat: 0, lon: 0 },
        { nom: "Irak", lat: 0, lon: 0 },
        { nom: "Irán", lat: 0, lon: 0 },
        { nom: "Israel", lat: 0, lon: 0 },
        { nom: "Japón", lat: 0, lon: 0 },
        { nom: "Jordania", lat: 0, lon: 0 },
        { nom: "Kazajistán", lat: 0, lon: 0 },
        { nom: "Kirguistán", lat: 0, lon: 0 },
        { nom: "Kuwait", lat: 0, lon: 0 },
        { nom: "Laos", lat: 0, lon: 0 },
        { nom: "Líbano", lat: 0, lon: 0 },
        { nom: "Malasia", lat: 0, lon: 0 },
        { nom: "Maldivas", lat: 0, lon: 0 },
        { nom: "Mongolia", lat: 0, lon: 0 },
        { nom: "Nepal", lat: 0, lon: 0 },
        { nom: "Omán", lat: 0, lon: 0 },
        { nom: "Pakistán", lat: 0, lon: 0 },
        { nom: "Rusia", lat: 0, lon: 0 },
        { nom: "Singapur", lat: 0, lon: 0 },
        { nom: "Siria", lat: 0, lon: 0 },
        { nom: "Sri Lanka", lat: 0, lon: 0 },
        { nom: "Tailandia", lat: 0, lon: 0 },
        { nom: "Tayikistán", lat: 0, lon: 0 },
        { nom: "Timor Oriental", lat: 0, lon: 0 },
        { nom: "Turkmenistán", lat: 0, lon: 0 },
        { nom: "Turquía", lat: 0, lon: 0 },
        { nom: "Uzbekistán", lat: 0, lon: 0 },
        { nom: "Vietnam", lat: 0, lon: 0 },
        { nom: "Yemen", lat: 0, lon: 0 },
      ],
      oceania: [
        { nom: "Australia", lat: -24, lon: 133 },
        { nom: "Islas Marshall", lat: 0, lon: 0 },
        { nom: "Islas Salomón", lat: 0, lon: 0 },
        { nom: "Kiribati", lat: 0, lon: 0 },
        { nom: "Macronesia", lat: 0, lon: 0 },
        { nom: "Nueva Zelanda", lat: -43, lon: 170 },
        { nom: "Palaos", lat: 0, lon: 0 },
        { nom: "Papúa Nueva Guinea", lat: 0, lon: 0 },
        { nom: "Tonga", lat: 0, lon: 0 },
      ]
    }
    


module.exports = paises;